spring:
  cloud:
    gateway:
      routes:
        - id: test_route
          uri: https://weibo.com/u/6395760665
          predicates:
            - Query=url,baidu
        - id: qq_route
          uri: https://www.qq.com
          predicates:
            - Query=url,qq